-- Seed data for listings
-- Note: id will be auto-generated as UUID
INSERT INTO listings (
  title, slug, location, location_value, category, property_type,
  price_czk, beds, baths, area_sqm, description, highlights, status,
  image, coordinates, postal_code, street_address, features
) VALUES
(
  'Masarykova Garden Villa',
  'masarykova-garden-villa',
  'Masarykova čtvrť, Brno',
  'masarykova-ctvrt',
  'homes-sale',
  'villa',
  28500000,
  5,
  4.5,
  448,
  'Elegant 1920s villa with restored Art Deco detailing, terraced gardens, and sweeping views over Špilberk Castle.',
  ARRAY['Panoramic terrace', 'Restored winter garden', 'Wine cellar & tasting room'],
  'featured',
  'https://images.unsplash.com/photo-1590490360182-663063ad3b66?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.1909, 16.5898],
  '602 00',
  'Hlinky 45',
  ARRAY['Terrace', 'Wine Cellar', 'Garden']
),
(
  'Svratka Riverside Loft',
  'svratka-riverside-loft',
  'Brno-střed, Brno',
  'brno-stred',
  'homes-sale',
  'loft',
  16900000,
  3,
  2.5,
  238,
  'Minimalist loft with double-height living, bespoke millwork, and floor-to-ceiling glazing onto the river promenade.',
  ARRAY['12-metre glass facade', 'Integrated smart home', 'Private parking in courtyard'],
  'featured',
  'https://images.unsplash.com/photo-1529429617124-aee0014819be?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.1916, 16.613],
  '602 00',
  'Poštovská 12',
  ARRAY['River View', 'Smart Home']
),
(
  'Královo Pole Skyline Residence',
  'kralovo-pole-skyline-residence',
  'Královo Pole, Brno',
  'kralovo-pole',
  'homes-sale',
  'villa',
  22400000,
  4,
  3.5,
  332,
  'Contemporary hillside home oriented to south-west sunsets, featuring a wellness suite and eco-efficient technologies.',
  ARRAY['Wellness spa & sauna', 'Photovoltaic array', 'Landscaped roof garden'],
  'featured',
  'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.2262, 16.5911],
  '612 00',
  'Chaloupkova 5',
  ARRAY['Rooftop Garden', 'Wellness']
),
(
  'Žabovřesky Townhouse',
  'zabovresky-townhouse',
  'Žabovřesky, Brno',
  'zabovresky',
  'homes-sale',
  'townhouse',
  13800000,
  3,
  2.5,
  199,
  'Bright townhouse in a quiet residential enclave with a landscaped courtyard, flexible studio, and secure parking.',
  ARRAY['Inner courtyard garden', 'Flexible studio level', 'Secure underground parking'],
  NULL,
  'https://images.unsplash.com/photo-1616594039964-6789ad4c5206?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.2169, 16.572],
  '616 00',
  'Sochorova 28',
  ARRAY['Courtyard', 'Studio Space']
),
(
  'Vinohrady Design Penthouse',
  'vinohrady-design-penthouse',
  'Vinohrady, Prague',
  'prague-cz',
  'homes-sale',
  'penthouse',
  34900000,
  4,
  3.5,
  374,
  'Expansive Prague penthouse with skyline terraces, bespoke Czech design finishes, and direct lift access.',
  ARRAY['Wraparound terrace', 'Private lift lobby', 'Custom Czech design studio'],
  'featured',
  'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
  ARRAY[50.0766, 14.4413],
  '120 00',
  'Vinohradská 32',
  ARRAY['Private Terrace', 'Lift Lobby']
),
(
  'Špilberk Investment Palace',
  'spilberk-investment-palace',
  'Brno-střed, Brno',
  'brno-stred',
  'investment-building',
  'mixed-use',
  49500000,
  NULL,
  NULL,
  833,
  'Mixed-use historic building steps from Freedom Square, featuring retail arcades, boutique offices, and furnished residences.',
  ARRAY['Retail frontage on Česká', 'Boutique serviced apartments', 'Heritage restoration plan'],
  NULL,
  'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.1947, 16.6035],
  '602 00',
  'Česká 18',
  ARRAY['Retail Frontage', 'Serviced Apartments']
),
(
  'Olomouc Heritage Residence',
  'olomouc-heritage-residence',
  'Historic Centre, Olomouc',
  'olomouc',
  'homes-sale',
  'townhouse',
  18600000,
  4,
  3,
  280,
  'Revitalised townhouse overlooking Upper Square with vaulted interiors, private courtyard, and preserved fresco ceilings.',
  ARRAY['Sunny internal courtyard', 'Restored ceiling frescoes', 'Dual residential entrances'],
  NULL,
  'https://images.unsplash.com/photo-1590073242678-70f12c6a8991?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.5938, 17.2518],
  '779 00',
  'Horní náměstí 7',
  ARRAY['Courtyard', 'Historic Interior']
),
(
  'Technology Park Executive Lofts',
  'brno-tech-campus-lofts',
  'Technology Park, Brno',
  'brno-tech',
  'homes-rent',
  'loft',
  11900000,
  2,
  2,
  156,
  'Smart-enabled lofts adjacent to the Brno Technology Park with private terraces and premium cowork amenities.',
  ARRAY['Smart home automation', 'Private terrace lounge', 'Resident cowork studio'],
  NULL,
  'https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?auto=format&fit=crop&w=1200&q=80',
  ARRAY[49.2289, 16.5712],
  '612 00',
  'Technická 10',
  ARRAY['Smart Home', 'Cowork Access']
)
ON CONFLICT (slug) DO NOTHING;

